#!/bin/sh
set -e

if [ ! -d /home/"${SSH_USERNAME}"/.ssh ]; then
  adduser -D -u 1337 "${SSH_USERNAME}"
  mkdir -p /home/"${SSH_USERNAME}"/.ssh
  chmod 700 /home/"${SSH_USERNAME}"/.ssh
  chown "${SSH_USERNAME}":"${SSH_USERNAME}" /home/"${SSH_USERNAME}"/.ssh
fi

if [ -n "${AUTHORIZED_KEYS}" ]; then
    echo "${AUTHORIZED_KEYS}" > /home/"${SSH_USERNAME}"/.ssh/authorized_keys
elif [ -f /authorized_keys ]; then
    cp /authorized_keys /home/"${SSH_USERNAME}"/.ssh/authorized_keys
else
    echo "Env var AUTHORIZED_KEYS or /authorized_keys required."
    exit 1
fi

chown "${SSH_USERNAME}":"${SSH_USERNAME}" /home/"${SSH_USERNAME}"/.ssh/authorized_keys

exec "$@"
