name: CI/CD

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: docker-buildx-${{ github.sha }}
          restore-keys: docker-buildx-

      - name: Build
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache/latest \
            --cache-to type=local,dest=/tmp/.buildx-cache/latest \
            --output type=docker \
            --tag kooldev/sshd:latest \
            .

      - name: Tests
        run: |
          AUTHORIZED_KEYS="something"
          docker run --rm --init -e AUTHORIZED_KEYS_KOOL=$AUTHORIZED_KEYS kooldev/sshd which sshd

          touch authorized_keys_kool
          docker run --rm --init -v "$(pwd)/authorized_keys_kool:/authorized_keys_kool" kooldev/sshd which sshd

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-sshd'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/docker-sshd'
        run: docker push kooldev/sshd:latest
